(part "RAPC742X"
    (packageRef "RAPC742X")
    (interface
        (port "1" (symbPinId 1) (portName "SLEEVE") (portType INOUT))
        (port "2" (symbPinId 2) (portName "SHUNT") (portType INOUT))
        (port "3" (symbPinId 3) (portName "TIP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "Switchcraft")
    (property "Manufacturer_Part_Number" "RAPC742X")
    (property "Mouser_Part_Number" "502-RAPC742X")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Switchcraft/RAPC742X?qs=mcPJWgAPNrdJm2lvzLuBfQ%3D%3D")
    (property "Arrow_Part_Number" "RAPC742X")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/rapc742x/switchcraft")
    (property "Description" "Jack, Power; PC Mount; 1 mm; 50 Milliohms (Max.); 250 VAC for 1 Minute; 3 A")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/RAPC742X.pdf")
    (property "symbolName1" "RAPC742X")
)
